CREATE DATABASE ADAM;
USE ADAM;
CREATE TABLE ADAM.CREDENTIAL_TYPE (
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name CHAR(150) NOT NULL,
	description CHAR(250) NOT NULL
) ENGINE = InnoDB;

CREATE TABLE ADAM.CREDENTIAL (
	id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name CHAR(255) NOT NULL,
	salt CHAR(250) NOT NULL,
	username CHAR(250),
	domain CHAR(250),
	password CHAR(250),
	authfile MEDIUMBLOB,
	description CHAR(250) NOT NULL,
	credential_type_id SMALLINT UNSIGNED NOT NULL,
	CONSTRAINT `fk_credential_type`
		FOREIGN KEY (credential_type_id) REFERENCES ADAM.CREDENTIAL_TYPE (id)
		ON DELETE CASCADE
		ON UPDATE RESTRICT
) ENGINE = InnoDB;
